# Generated by Django 6.0.6 on 2026-06-20 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCarnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.CharField(default='Mi Empresa', max_length=100)),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='templates/')),
                ('orientacion', models.CharField(choices=[('H', 'Horizontal'), ('V', 'Vertical')], default='H', max_length=1)),
                ('ancho_mm', models.FloatField(default=85.6)),
                ('alto_mm', models.FloatField(default=54.0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nombre', 'Nombre'), ('cargo', 'Cargo'), ('empresa', 'Empresa'), ('codigo', 'Código'), ('qr', 'Código QR'), ('foto', 'Foto'), ('logo', 'Logo Empresa'), ('barcode', 'Código de Barras'), ('identificacion', 'DNI/ID'), ('telefono', 'Teléfono'), ('num_empleado', 'N° Empleado'), ('texto', 'Texto libre')], max_length=20)),
                ('texto_fijo', models.CharField(blank=True, max_length=200, null=True)),
                ('x', models.FloatField(default=20)),
                ('y', models.FloatField(default=20)),
                ('width', models.FloatField(default=150)),
                ('height', models.FloatField(default=30)),
                ('font_size', models.IntegerField(default=16)),
                ('font_family', models.CharField(default='Arial', max_length=50)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('background_color', models.CharField(blank=True, default='', help_text='Hex o vacío', max_length=7, verbose_name='Color fondo')),
                ('font_weight', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Negrita')], default='normal', max_length=10, verbose_name='Grosor')),
                ('text_align', models.CharField(choices=[('left', 'Izquierda'), ('center', 'Centro'), ('right', 'Derecha')], default='left', max_length=10, verbose_name='Alineación')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='carnets.plantillacarnet')),
            ],
        ),
    ]
