# Generated by Django 6.0.6 on 2026-06-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='Persona de contacto')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='RUC / Tax ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, default='Perú', max_length=100, verbose_name='País')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#000000', help_text='Hex: #RRGGBB', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#1E40AF', max_length=7, verbose_name='Color secundario')),
                ('subscription_plan', models.CharField(choices=[('free', 'Gratuito (100 tarjetas)'), ('basic', 'Básico (1,000 tarjetas)'), ('premium', 'Premium (10,000 tarjetas)'), ('enterprise', 'Enterprise (Ilimitado)')], default='free', max_length=20, verbose_name='Plan de suscripción')),
                ('subscription_start', models.DateField(auto_now_add=True, verbose_name='Inicio de suscripción')),
                ('subscription_end', models.DateField(blank=True, null=True, verbose_name='Fin de suscripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='companies_c_is_acti_03043b_idx'), models.Index(fields=['subscription_plan'], name='companies_c_subscri_e613aa_idx')],
            },
        ),
    ]
